# this will tag PRs that are ready for release and automerge them
name: Automerge passing PR
env:
  pr_number: ${{ join(join('',github.event.pull_request.number)join('', github.event.issue.number)) }}
on:
  issue_comment:
    types: [created]
  pull_request:
jobs:
  # when /release is typed from trilom or when a PR is tagged
  automerge:
    name: automerge a PR
    runs-on: ubuntu-latest
    steps:
        - run: echo $pr_number